"""Saint-of-the-day entries for Ora (original text). Keyed MM-DD.
'efMatch' lets build_saints.py take the Collect from the 1962 Missal when that saint is kept there.
'query' is the Wikimedia Commons search used to find a public-domain painting."""

SAINTS = {
 "10-06": dict(name="Saint Bruno", dates="c. 1030–1101 · Cologne and Calabria", efMatch="Bruno",
  history="A celebrated teacher at Reims who turned down a bishopric to seek God in silence. In 1084 he and six companions settled in the mountains of the Chartreuse, near Grenoble, and founded the Carthusians, monks who live as hermits in community. The order has never needed reform, it is said, because it was never deformed.",
  meditation="Stat crux dum volvitur orbis: the cross stands still while the world turns. Find ten minutes of silence today and let the world turn without you.",
  query="Saint Bruno painting Zurbarán OR Le Sueur"),
 "10-07": dict(name="Our Lady of the Rosary", dates="Instituted 1571", efMatch="Rosary",
  history="On 7 October 1571 a Christian fleet defeated the Ottoman navy at Lepanto, while confraternities across Europe prayed the Rosary at Pope Pius V's request. He instituted a feast of Our Lady of Victory, later renamed Our Lady of the Rosary. October became the month of the Rosary.",
  meditation="Pray one decade slowly today. Let each Hail Mary be one step beside Our Lady through the life of her Son.",
  query="Madonna of the Rosary painting Caravaggio"),
 "10-09": dict(name="Saint John Henry Newman", dates="1801–1890 · London, Oxford and Birmingham",
  history="The leading Anglican thinker of his age, Newman followed his study of the early Church into the Catholic Church in 1845, at great personal cost. He founded the Birmingham Oratory, wrote The Idea of a University and The Dream of Gerontius, and was made a cardinal in 1879. He was canonised in 2019.",
  prayer="Lead, kindly Light, amid the encircling gloom, lead Thou me on! The night is dark, and I am far from home; lead Thou me on! Keep Thou my feet; I do not ask to see the distant scene; one step enough for me.",
  prayerSource="John Henry Newman, 1833",
  meditation="One step enough for me. What is the one step God is asking of you today?",
  query="John Henry Newman portrait Millais"),
 "10-15": dict(name="Saint Teresa of Ávila", dates="1515–1582 · Castile", efMatch="Teresa",
  history="A Carmelite nun who, after years of lukewarm prayer, was converted before an image of the wounded Christ. She reformed her order, founding seventeen convents of the Discalced Carmelites, and wrote The Way of Perfection and The Interior Castle. In 1970 she became the first woman named a Doctor of the Church.",
  prayer="Let nothing disturb you, let nothing frighten you. All things are passing; God never changes. Patience obtains all things. Whoever has God lacks nothing. God alone suffices.",
  prayerSource="Saint Teresa's bookmark",
  meditation="Prayer, Teresa said, is nothing else than an intimate sharing between friends. Speak to Christ today as a friend.",
  query="Saint Teresa of Avila painting Rubens"),
 "10-16": dict(name="Saint Margaret Mary Alacoque", dates="1647–1690 · Burgundy",
  history="A Visitation nun at Paray-le-Monial to whom Christ revealed His Sacred Heart in a series of visions between 1673 and 1675. Doubted by her community, she persevered, and the devotion to the Sacred Heart spread through the whole Church, with its First Fridays and the feast of the Sacred Heart.",
  meditation="Behold this Heart which has so loved men. Make an act of reparation today for indifference to that love.",
  query="Margaret Mary Alacoque Sacred Heart painting"),
 "10-17": dict(name="Saint Ignatius of Antioch", dates="Died c. 107 · Antioch and Rome", efMatch="Ignatius",
  history="Bishop of Antioch, taken under guard to Rome to be thrown to the beasts. On the way he wrote seven letters to the churches, the earliest witness outside Scripture to bishops, the Eucharist and the name 'Catholic Church'.",
  meditation="I am the wheat of God, and I am ground by the teeth of wild beasts, that I may be found the pure bread of Christ. What in you does God wish to grind into bread?",
  query="Ignatius of Antioch martyrdom painting"),
 "10-18": dict(name="Saint Luke the Evangelist", dates="First century", efMatch="Luke",
  history="A Greek physician and companion of Saint Paul who wrote the third Gospel and the Acts of the Apostles. Only Luke gives us the Annunciation, the Visitation, the Magnificat, the Benedictus, the shepherds, the Prodigal Son and the Good Samaritan. Tradition says he painted the first icon of the Virgin.",
  meditation="Read Luke 15 slowly today, the lost sheep, the lost coin and the lost son.",
  query="Saint Luke drawing the Virgin painting Rogier van der Weyden"),
 "10-22": dict(name="Saint John Paul II", dates="1920–2005 · Kraków and Rome",
  history="Karol Wojtyła, actor, philosopher and bishop of Kraków, was elected pope in 1978, the first non-Italian in 455 years. He helped bring down communism in Eastern Europe, travelled to 129 countries, gave the Church the Theology of the Body and the Catechism, and bore his long final illness in public.",
  meditation="Do not be afraid. Open wide the doors for Christ. Which door have you kept shut?"),
 "10-28": dict(name="Saints Simon and Jude", dates="Apostles and martyrs", efMatch="Simon",
  history="Two of the Twelve, kept together because tradition holds that they preached in Persia and were martyred there together. Simon is called the Zealot; Jude, also named Thaddeus, wrote the short letter that bears his name and is the patron of hopeless causes.",
  meditation="Bring to Saint Jude the situation you have given up on.",
  query="Saint Jude Thaddeus painting"),
 "11-01": dict(name="All Saints", dates="Solemnity", efMatch="All Saints",
  history="The Church honours in one feast all who have reached heaven, the great multitude which no man could number, most of them known only to God. The feast was fixed on 1 November in the eighth century and is a holy day of obligation.",
  fast="Until 1955 the day before, 31 October, was kept as a vigil of fasting and abstinence. Some still keep it as a private devotion.",
  meditation="Holiness is not for a few. Ask one saint to be your companion this month.",
  query="Fra Angelico Forerunners of Christ with Saints and Martyrs"),
 "11-02": dict(name="All Souls", dates="Commemoration of all the faithful departed", efMatch="Souls",
  history="The day after All Saints the Church prays for all who have died in God's friendship but still await purification. Priests may offer three Masses today. Through November Catholics visit graves and pray for their dead.",
  prayer="Eternal rest grant unto them, O Lord, and let perpetual light shine upon them. May they rest in peace. Amen.",
  prayerSource="Traditional prayer for the dead",
  fast="From 1 to 8 November a plenary indulgence may be gained for the souls in purgatory by visiting a cemetery and praying for the dead.",
  meditation="Name your dead before God today, one by one.",
  query="Office of the Dead miniature Book of Hours burial"),
 "11-03": dict(name="Saint Martin de Porres", dates="1579–1639 · Lima, Peru",
  history="Son of a Spanish nobleman and a freed slave, Martin was a Dominican lay brother who served as barber, infirmarian and almoner. He cared for the sick, the poor, slaves and even animals, and was known for his humility and his gift of healing.",
  meditation="He called himself 'the mulatto dog'. Do one hidden act of service today that no one will thank you for.",
  query="Martin de Porres painting"),
 "11-04": dict(name="Saint Charles Borromeo", dates="1538–1584 · Milan", efMatch="Charles",
  history="Nephew of Pope Pius IV and cardinal archbishop of Milan, he led the reform of the Church after the Council of Trent, founding seminaries and visiting every parish of his huge diocese. In the plague of 1576 he stayed in the city to nurse the sick when the governor fled.",
  meditation="Reform begins at home. Choose one habit to amend this week.",
  query="Saint Charles Borromeo painting plague"),
 "11-09": dict(name="Dedication of the Lateran Basilica", dates="Rome, 324", efMatch="Lateran",
  history="Saint John Lateran, not Saint Peter's, is the cathedral of the Pope as Bishop of Rome, 'mother and head of all the churches of the city and the world'. It was dedicated by Pope Sylvester in 324, soon after the Church was freed from persecution.",
  meditation="You are God's temple. Pray for your own parish church and its priest today.",
  query="Archbasilica of Saint John Lateran painting interior"),
 "11-10": dict(name="Saint Leo the Great", dates="Died 461 · Rome", efMatch="Leo",
  history="Pope at a time of collapse, Leo defined the Church's faith that Christ is one Person in two natures, a teaching the Council of Chalcedon received with the cry 'Peter has spoken through Leo'. He met Attila the Hun outside Rome and persuaded him to turn back.",
  meditation="Christian, remember your dignity. What would change if you believed it today?",
  query="Raphael Meeting of Leo the Great and Attila"),
 "11-11": dict(name="Saint Martin of Tours", dates="c. 316–397 · Gaul", efMatch="Martin",
  history="A Roman soldier who, at the gates of Amiens, cut his cloak in half for a freezing beggar and that night saw Christ wearing it. He became a monk and bishop of Tours, one of the first saints venerated who was not a martyr. His feast fell on the day the 1918 Armistice was signed.",
  fast="Martinmas once began 'Saint Martin's Lent', a forty-day fast before Christmas. Consider an Advent discipline beginning today.",
  meditation="Whom will you give half your cloak to this week?",
  query="Saint Martin dividing his cloak painting El Greco"),
 "11-15": dict(name="Saint Albert the Great", dates="c. 1200–1280 · Cologne", efMatch="Albert",
  history="A Dominican friar and bishop who mastered every science of his day, from theology to botany and astronomy, and taught Thomas Aquinas. He is the patron saint of scientists.",
  meditation="Faith and reason are two wings. Learn one new thing today and thank God for it.",
  query="Albertus Magnus fresco Tommaso da Modena"),
 "11-16": dict(name="Saint Margaret of Scotland", dates="c. 1045–1093 · Dunfermline", efMatch="Margaret",
  history="An English princess who married King Malcolm III of Scotland. She reformed the Church in Scotland, founded the abbey at Dunfermline and the Queen's Ferry for pilgrims to Saint Andrews, and fed the poor at her own table before she ate.",
  meditation="Holiness in marriage and family life: do one thing today for those you live with.",
  query="Saint Margaret of Scotland painting"),
 "11-17": dict(name="Saint Elizabeth of Hungary", dates="1207–1231 · Thuringia", efMatch="Elizabeth",
  history="A king's daughter and a landgravine who, widowed at twenty, gave her wealth to build a hospital at Marburg and served the sick there herself. She died at twenty-four. Legend says bread she carried to the poor turned to roses when her husband asked to see it.",
  meditation="Give something today that costs you.",
  query="Saint Elizabeth of Hungary roses painting"),
 "11-21": dict(name="The Presentation of the Blessed Virgin Mary", dates="Feast", efMatch="Presentation",
  history="An ancient tradition tells that Joachim and Anne brought Mary as a small child to the Temple in Jerusalem to be offered to God. The feast honours her total dedication to God from the beginning of her life.",
  meditation="Offer yourself again to God today, as you are.",
  query="Presentation of the Virgin in the Temple painting Titian"),
 "11-22": dict(name="Saint Cecilia", dates="Third century · Rome", efMatch="Cecilia",
  history="A Roman virgin and martyr whose name is said in the Roman Canon. The story of her martyrdom says she sang to God in her heart, and so she became the patron of music and musicians. Her body was found incorrupt in 1599.",
  meditation="Sing, or listen to, one piece of sacred music today with full attention.",
  query="Saint Cecilia painting Raphael Ecstasy"),
 "11-25": dict(name="Saint Catherine of Alexandria", dates="Fourth century · Egypt", efMatch="Catherine",
  history="A learned young woman of Alexandria who, tradition says, out-argued fifty pagan philosophers sent by the emperor and converted them. Sentenced to be broken on a spiked wheel, which shattered at her touch, she was beheaded. She was one of the voices heard by Saint Joan of Arc.",
  meditation="Love the truth enough to learn it well.",
  query="Saint Catherine of Alexandria painting Caravaggio"),
 "11-30": dict(name="Saint Andrew the Apostle", dates="First century · Patron of Scotland", efMatch="Andrew",
  history="A fisherman of Bethsaida, disciple of John the Baptist, and the first apostle called by Christ. He brought his brother Simon Peter to Jesus. Tradition says he was crucified on an X-shaped cross at Patras in Greece, the saltire of Scotland's flag.",
  fast="The traditional Saint Andrew Christmas Novena begins today: 'Hail and blessed be the hour and moment in which the Son of God was born…', said fifteen times a day until Christmas.",
  meditation="Andrew's first act as a disciple was to bring someone else to Jesus. Whom will you bring?",
  query="Martyrdom of Saint Andrew painting Murillo"),
 "12-03": dict(name="Saint Francis Xavier", dates="1506–1552 · Navarre to China", efMatch="Francis Xavier",
  history="One of the first companions of Saint Ignatius of Loyola, he became the greatest missionary since Saint Paul, preaching in India, the Malay archipelago and Japan, and baptising tens of thousands. He died on an island off the coast of China, waiting to enter it.",
  meditation="What does it profit a man to gain the whole world and lose his soul? Ignatius asked him this until he gave his life away.",
  query="Saint Francis Xavier painting Rubens miracles"),
 "12-06": dict(name="Saint Nicholas", dates="Fourth century · Myra", efMatch="Nicholas",
  history="Bishop of Myra in Asia Minor, remembered for secretly giving three bags of gold to save three poor girls from ruin by throwing them through a window at night. From that hidden charity came Santa Claus.",
  meditation="Give something today in secret.",
  query="Saint Nicholas dowry three girls painting Fra Angelico"),
 "12-07": dict(name="Saint Ambrose", dates="c. 340–397 · Milan", efMatch="Ambrose",
  history="A Roman governor acclaimed bishop of Milan by the people while still unbaptised. He wrote hymns still sung in the Divine Office, defended the Church against emperors, and his preaching helped bring Saint Augustine to faith.",
  meditation="Ambrose made an emperor do public penance. Where do you need to repent publicly, even in a small way?",
  query="Saint Ambrose painting"),
 "12-08": dict(name="The Immaculate Conception", dates="Solemnity", efMatch="Immaculate",
  history="The Church teaches that Mary, by a singular grace of God and in view of the merits of Christ, was preserved free from all stain of original sin from the first moment of her conception. Pius IX defined the dogma in 1854; four years later Our Lady told Bernadette at Lourdes, 'I am the Immaculate Conception.'",
  prayer="O Mary, conceived without sin, pray for us who have recourse to thee.",
  prayerSource="The Miraculous Medal, 1830",
  meditation="Tota pulchra es, Maria. Ask her to help you hate one particular sin.",
  query="Immaculate Conception painting Murillo"),
 "12-12": dict(name="Our Lady of Guadalupe", dates="Mexico, 1531",
  history="In December 1531 the Virgin appeared to Juan Diego, a poor Aztec convert, on the hill of Tepeyac. As a sign for the bishop she filled his cloak with Castilian roses, and when he opened it her image was found printed on it. Millions were baptised in the years that followed.",
  meditation="Am I not here, I who am your mother? Bring her your greatest worry.",
  query="Our Lady of Guadalupe tilma"),
 "12-13": dict(name="Saint Lucy", dates="Died 304 · Syracuse", efMatch="Lucy",
  history="A young Christian of Syracuse in Sicily who gave her dowry to the poor and was martyred under Diocletian. Her name means light, and her feast, near the darkest days of the year, is kept with candles, especially in Scandinavia. She is named in the Roman Canon.",
  meditation="Be a light in someone's darkness today.",
  query="Saint Lucy painting Francesco del Cossa"),
 "12-14": dict(name="Saint John of the Cross", dates="1542–1591 · Castile", efMatch="John of the Cross",
  history="A Carmelite friar who worked with Saint Teresa of Ávila to reform his order and was imprisoned by his own brothers for it. In a tiny cell in Toledo he wrote his greatest poetry. The Dark Night and The Living Flame of Love map the way of the soul to union with God.",
  meditation="In the evening of life we shall be judged on love.",
  query="Saint John of the Cross painting Zurbarán"),
 "12-26": dict(name="Saint Stephen", dates="First martyr", efMatch="Stephen",
  history="One of the seven deacons chosen by the apostles to serve the poor, Stephen was stoned to death in Jerusalem for his preaching, praying for his killers as he died. A young man named Saul held the cloaks of those who stoned him.",
  meditation="Lord, do not hold this sin against them. Forgive someone today.",
  query="Stoning of Saint Stephen painting Rembrandt"),
 "12-27": dict(name="Saint John the Apostle", dates="First century", efMatch="John",
  history="The beloved disciple, who leaned on the Lord's breast at the Last Supper, stood at the foot of the cross and took Mary into his home. He wrote the fourth Gospel, three letters and the Apocalypse, and is the only apostle believed not to have died a martyr.",
  meditation="Little children, love one another. In old age, they say, this was all he would preach.",
  query="Saint John the Evangelist on Patmos painting"),
 "12-28": dict(name="The Holy Innocents", dates="Martyrs", efMatch="Innocents",
  history="The children of Bethlehem killed by King Herod in his attempt to destroy the newborn Christ. The Church honours them as martyrs, who confessed Christ not by speaking but by dying.",
  meditation="Pray today for children who suffer, born and unborn.",
  query="Massacre of the Innocents painting Giotto"),
 "12-29": dict(name="Saint Thomas Becket", dates="1120–1170 · Canterbury", efMatch="Thomas",
  history="Chancellor and friend of King Henry II, Thomas became Archbishop of Canterbury and defended the freedom of the Church against the king. Four knights murdered him in his own cathedral. Canterbury became one of the great pilgrim shrines of Europe.",
  meditation="Willing to die for the Church: what would you be willing to give up for her?",
  query="Murder of Thomas Becket miniature manuscript"),
}

# Fuller entries: a longer life, a prayer to the saint and a fast or penance.
# 'always' shows the entry whatever the calendar data says (used for national feasts such as Newman in England and Wales).
SAINTS["10-08"] = dict(name="Saint Bridget of Sweden", dates="1303–1373 · Sweden and Rome", efMatch="Bridget", calendars=["EF"],
  history="A Swedish noblewoman, wife and mother of eight, who after her husband's death founded the Order of the Most Holy Saviour and spent her last twenty-four years in Rome, praying and pleading for the reform of the Church.",
  query="Saint Bridget of Sweden painting")

EXTRA = {
 "10-06": dict(
  life="Born in Cologne around 1030, Bruno became master of the cathedral school at Reims, where one of his pupils later became Pope Urban II. He stood against a simoniac archbishop and lost his post for it. In 1084, with six companions, he went to Bishop Hugh of Grenoble, who had dreamed of seven stars guiding him to a wild valley in the Alps. There they built the Grande Chartreuse. Called to Rome by his old pupil, Bruno longed for solitude and was allowed to found a second hermitage at La Torre in Calabria, where he died in 1101. He was never formally canonised; his cult was approved in 1514.",
  prayerTo="Saint Bruno, you left honours and learning to seek God alone in the silence of the mountains. Teach me to love silence, to guard my heart from noise and distraction, and to find in stillness the God who speaks there. Pray for me, that I may seek Him first. Amen.",
  penance="Keep an hour of silence today: no phone, no music, no news. The Carthusians also abstain from meat for life; consider a meatless day."),
 "10-07": dict(
  life="Tradition links the Rosary to Saint Dominic in the thirteenth century; it grew into its familiar form of fifteen decades by the sixteenth. Before the Battle of Lepanto in 1571, Pope Pius V asked all Christendom to pray it, and credited the victory to Our Lady's intercession. Gregory XIII gave the feast its present name in 1573. Popes since Leo XIII have written on the Rosary, and in 2002 John Paul II added the Luminous Mysteries.",
  prayerTo="Queen of the Most Holy Rosary, you walked with your Son from the crib to the cross to the glory of heaven. Take my hand as I pray, and let the mysteries of His life become the pattern of mine. Pray for us, that we may be made worthy of the promises of Christ. Amen.",
  penance="Pray all five decades today, kneeling if you can, for an intention bigger than yourself: peace, or the conversion of someone you love."),
 "10-08": dict(
  life="Bridget Birgersdotter was married at thirteen to Ulf Gudmarsson and bore eight children, among them Saint Catherine of Sweden. She served at the royal court and, after Ulf died in 1344, gave herself wholly to prayer. Her visions, recorded as the Revelations, called kings and popes to repentance and urged the papacy to return from Avignon to Rome. She founded a double monastery at Vadstena, went to Rome for the Jubilee of 1350 and never went home, dying there in 1373 after a pilgrimage to the Holy Land. John Paul II named her a patron saint of Europe in 1999.",
  prayerTo="Saint Bridget, wife, mother and widow, you loved Christ crucified and were not afraid to speak the truth to the powerful. Help me to meditate on His Passion, to serve my family faithfully, and to pray for the renewal of the Church. Amen.",
  penance="Bridget meditated daily on the Passion. Spend fifteen minutes today with a crucifix, and make a small sacrifice in honour of the wounds of Christ."),
 "10-09": dict(
  life="Newman was the leading light of the Oxford Movement, which sought to recover the Catholic heritage of the Church of England. His study of the Fathers led him, slowly and painfully, to conclude that the Catholic Church was the Church they knew. On 9 October 1845, the date of his feast, he was received by Blessed Dominic Barberi at Littlemore. He lost friends, position and income. As an Oratorian in Birmingham he preached, taught, founded a school and wrote the Apologia pro Vita Sua in reply to a public attack on his honesty. Leo XIII made him a cardinal in 1879; his motto was Cor ad cor loquitur, heart speaks to heart. Benedict XVI beatified him in Birmingham in 2010.",
  prayerTo="Saint John Henry, you followed the kindly Light through doubt and loss to the fullness of the faith. Pray for all who search for truth, for those who have drifted from the Church, and for me, that I may take the next step God shows me, and trust Him with the rest. Amen.",
  penance="Newman gave up everything for conscience. Give up something you lean on today, and pray for someone you know who is searching.",
  always=True),
 "10-15": dict(
  life="Teresa de Ahumada entered the Carmelite convent of the Incarnation at Ávila in 1535. For nearly twenty years her prayer was half-hearted, until in 1554 she was overcome before an image of the wounded Christ. From then on she lived a life of deep prayer and mystical graces. In 1562 she founded the small convent of Saint Joseph, returning to the strict original rule, and with Saint John of the Cross she carried the reform to the friars. She travelled Spain in a covered cart, founding convents in spite of illness and opposition, and wrote with humour and honesty about the soul's journey to God. She died at Alba de Tormes in 1582 and was canonised in 1622.",
  prayerTo="Saint Teresa, you learned that God alone suffices. Teach me to pray as a friend speaks with a friend, to persevere when prayer is dry, and to keep a good humour on the way. Pray for me, that nothing may disturb me and nothing frighten me. Amen.",
  penance="Teresa insisted on daily mental prayer. Give God fifteen minutes of quiet prayer today, even if it feels like nothing happens."),
 "10-16": dict(
  life="Margaret Mary entered the Visitation monastery at Paray-le-Monial in 1671. In a series of revelations Christ showed her His Heart, burning with love and wounded by ingratitude, and asked for a feast in its honour, for Communion on the first Friday of each month, and for an hour of prayer on Thursday nights in memory of His agony in Gethsemane. Her community thought her deluded until the Jesuit Saint Claude de la Colombière recognised the visions as genuine. The devotion she spread became one of the most widely loved in the Church. She was canonised in 1920.",
  prayerTo="Saint Margaret Mary, you saw the Heart that has so loved the world. Pray that my cold heart may be warmed by it, that I may make reparation for my sins and the sins of the world, and that I may rest in that Heart at the hour of my death. Amen.",
  penance="Keep the Holy Hour tonight or next Thursday, an hour of prayer with Christ in Gethsemane, and plan to receive Communion on the next First Friday."),
 "10-17": dict(
  life="Ignatius was the third bishop of Antioch, where the disciples were first called Christians. Arrested under Trajan around 107, he was taken in chains across Asia Minor to Rome. On the way he wrote seven letters, to the Ephesians, Magnesians, Trallians, Romans, Philadelphians and Smyrnaeans, and to Bishop Polycarp. They are the earliest writings we have that speak of bishops, priests and deacons, of the Eucharist as the flesh of Christ, and of 'the Catholic Church'. He begged the Christians of Rome not to try to save him. He died in the arena.",
  prayerTo="Saint Ignatius, you went to your death longing to be wheat ground into the bread of Christ. Pray that I may love the Eucharist as you did, stay close to the Church, and not shrink from what following Christ will cost. Amen.",
  penance="Go to a weekday Mass if you can, or make a spiritual communion, offering it for Christians persecuted for their faith today."),
 "10-18": dict(
  life="Saint Paul calls him 'Luke, the most dear physician'. A Gentile, probably from Antioch, Luke travelled with Paul, and the 'we' passages of Acts are his eyewitness account. He wrote his Gospel 'in order', having carefully traced everything from the beginning, and his pages carry the infancy of Christ, the parables of mercy and the canticles the Church still prays every day. He is the patron of physicians, surgeons and artists.",
  prayerTo="Saint Luke, physician and evangelist, you wrote of the mercy of God for the poor and the lost. Pray for all who care for the sick, for doctors and nurses, and for me, that I may know myself found by the Shepherd who came to seek the lost. Amen.",
  penance="Visit or call someone who is ill today, or pray for the doctors and nurses who care for them."),
 "10-22": dict(
  life="Born in Wadowice in 1920, Karol Wojtyła lost his mother, brother and father by the age of twenty. Under Nazi occupation he worked in a quarry, acted in an underground theatre and studied secretly for the priesthood. As bishop and archbishop of Kraków he defended the Church against the communist regime. Elected pope in 1978, he travelled the world, began World Youth Day, survived an assassin's bullet in 1981 and visited the gunman in prison to forgive him. He established Divine Mercy Sunday, gave the Church the Catechism, and died on its vigil in 2005. He was canonised in 2014.",
  prayerTo="Saint John Paul, you told the world not to be afraid. Pray for me in my fears, for families and young people, and for the Church you loved. Help me to open wide the doors of my life to Christ, and to trust in His mercy. Amen.",
  penance="Pray the Divine Mercy Chaplet at three o'clock today, and forgive someone who has wronged you, in your heart if not yet in person."),
 "10-28": dict(
  life="Simon is called the Zealot, perhaps because he had belonged to the party that resisted Rome, perhaps for his zeal. Jude, also called Thaddeus, is the apostle who asked Christ at the Last Supper why He would show Himself to them and not to the world. He wrote the short Letter of Jude, urging the faithful to 'contend for the faith once delivered to the saints'. Western tradition holds that the two preached together in Persia and were martyred there.",
  prayerTo="Saint Jude, faithful apostle and patron of things despaired of, I bring you what I cannot fix. Pray for me in this need, and teach me to trust in the God for whom nothing is impossible. Saint Simon, pray that my zeal may be for Christ alone. Amen.",
  penance="Offer a small fast today, perhaps a skipped meal or something you would usually enjoy, for a cause that seems hopeless."),
 "11-01": dict(
  life="The early Church kept the feasts of the martyrs on the anniversaries of their deaths. As their number grew beyond counting, a common feast emerged. In 609 Pope Boniface IV dedicated the Pantheon in Rome to Our Lady and all the martyrs, and in the eighth century Gregory III dedicated a chapel in Saint Peter's to all the saints on 1 November. Gregory IV extended the feast to the whole Church. It honours the saints we know and the vast company we do not, many of them ordinary men and women.",
  prayerTo="All you holy men and women, saints of God, pray for us. You have finished the race; help us to run it. Win for us the grace to become what God made us to be, and to join you in the vision of His face. Amen.",
  penance="Go to Mass, a holy day of obligation, and choose one saint to read about and imitate this month."),
 "11-02": dict(
  life="The custom of praying for the dead is older than Christianity; Judas Maccabeus 'made atonement for the dead, that they might be delivered from their sin'. Saint Odilo, abbot of Cluny, ordered a day of prayer for all the faithful departed around 998, and it spread through the whole Church. In 1915 Benedict XV allowed every priest to offer three Masses today, because of the dead of the First World War.",
  prayerTo="O Lord, by whose mercy the souls of the faithful find rest, grant to all my family, friends and benefactors who have died the forgiveness of their sins and the light of your face. Holy souls in purgatory, pray for us, and remember us when you come into your kingdom. Amen.",
  penance="Visit a cemetery and pray for the dead between 1 and 8 November; a plenary indulgence may be gained for the holy souls on each day."),
}
for _md, _x in EXTRA.items():
    if _md in SAINTS:
        SAINTS[_md].update(_x)
